# Site settings
title: Mr. Alshehri's Classes
email:
description: Discussion threads for some of Mr. Alshehri's classes
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://modhialshehri.github.io/" # the base hostname & protocol for your site
author: Mr. Alshehri
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

icon: fa-calculator # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
host: 0.0.0.0